import java.util.Scanner;

public class Main {
	public static void main(String[] args) {
		Scanner scanner = new Scanner(System.in);
		Robot robot = new Robot();
		System.out.print("Введите название робота: ");
		robot.setName(scanner.nextLine());
		robot.setChassis(new Chassis());
		System.out.print("Введите тип ходовой части: ");
		robot.getChassis().setType(scanner.nextLine());
		System.out.print("Введите собственную массу ходовой части (кг): ");
		robot.getChassis().setWeight(Double.parseDouble(scanner.nextLine()));
		robot.getChassis().setBattery(new Battery());
		System.out.print("Введите название (тип) аккумулятора: ");
		robot.getChassis().getBattery().setName(scanner.nextLine());
		System.out.print("Введите ёмкость аккумулятора (мА×ч): ");
		robot.getChassis().getBattery().setPowerPerHour(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите массу аккумулятора (кг): ");
		robot.getChassis().getBattery().setWeight(Double.parseDouble(scanner.nextLine()));
		robot.getChassis().setEngine(new Engine());
		System.out.print("Введите название двигателя: ");
		robot.getChassis().getEngine().setName(scanner.nextLine());
		System.out.print("Введите величину крутящего момента двигателя (Н×м): ");
		robot.getChassis().getEngine().setTorque(Double.parseDouble(scanner.nextLine()));
		System.out.print("Введите максимальную развиваемую двигателем нагрузку (кг): ");
		robot.getChassis().getEngine().setMoveableEffort(Double.parseDouble(scanner.nextLine()));
		System.out.print("Введите потребляемую мощность двигателя (мА): ");
		robot.getChassis().getEngine().setPower(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите массу двигателя (кг): ");
		robot.getChassis().getEngine().setWeight(Double.parseDouble(scanner.nextLine()));
		robot.getChassis().setTransmisson(new Transmisson());
		System.out.print("Введите название коробки передач: ");
		robot.getChassis().getTransmisson().setName(scanner.nextLine());
		System.out.print("Введите количество передач у коробки передач: ");
		robot.getChassis().getTransmisson().setLevelCount(Integer.parseInt(scanner.nextLine()));
		System.out.print("Поддерживает ли коробка передач реверс (true/false): ");
		robot.getChassis().getTransmisson().setReverse(Boolean.parseBoolean(scanner.nextLine()));
		System.out.print("Введите массу коробки передач (кг): ");
		robot.getChassis().getTransmisson().setWeight(Double.parseDouble(scanner.nextLine()));
		robot.setControlBlock(new ControlBlock());
		System.out.print("Введите название блока управления: ");
		robot.getControlBlock().setName(scanner.nextLine());
		System.out.print("Введите частоту процессора блока управления (ГГц): ");
		robot.getControlBlock().setClockFrequency(Double.parseDouble(scanner.nextLine()));
		System.out.print("Введите объём оперативной памяти блока управления (ГБ): ");
		robot.getControlBlock().setRamVolume(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите потребляемую мощность блока управления (мА): ");
		robot.getControlBlock().setPower(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите массу блока управления (кг): ");
		robot.getControlBlock().setWeight(Double.parseDouble(scanner.nextLine()));
		robot.setVideoSensor(new VideoSensor());
		System.out.print("Введите название видеосенсора (камеры): ");
		robot.getVideoSensor().setName(scanner.nextLine());
		System.out.print("Введите цветовой режим видеосенсора: ");
		robot.getVideoSensor().setColorMode(scanner.nextLine());
		System.out.print("Введите разрешение видеосенсора по ширине (пикселей): ");
		robot.getVideoSensor().setWidthResolution(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите разрешение видеосенсора по высоте (пикселей): ");
		robot.getVideoSensor().setHeightResolution(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите частоту развёртки видеосенсора (кадр/с): ");
		robot.getVideoSensor().setFps(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите потребляемую мощность видеосенсора (мА): ");
		robot.getVideoSensor().setPower(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите массу видеосенсора (кг): ");
		robot.getVideoSensor().setWeight(Double.parseDouble(scanner.nextLine()));
		robot.setSpeedSensor(new SpeedSensor());
		System.out.print("Введите название детектора скорости: ");
		robot.getSpeedSensor().setName(scanner.nextLine());
		System.out.print("Введите частоту срабатывания детектора скорости (с): ");
		robot.getSpeedSensor().setLatency(Double.parseDouble(scanner.nextLine()));
		System.out.print("Введите потребляемую мощность детектора скорости (мА): ");
		robot.getSpeedSensor().setPower(Integer.parseInt(scanner.nextLine()));
		System.out.print("Введите массу детектора скорости (кг): ");
		robot.getSpeedSensor().setWeight(Double.parseDouble(scanner.nextLine()));
		System.out.println("Максимальное время работы робота " + robot.timeOfWorking() + " ч");
		System.out.println("Максимальная грузоподъёмность робота " + robot.liftingCapacity() + " кг");
		scanner.close();
	}
}
